### ISSUE TITLE
Please add support for Symfony 7

### ISSUE THREAD

**Issue by Beninho** [infection/codeception-adapter#24]
This adapter is currently incompatible with Symfony 7.

In the **composer.json**:

```
        "symfony/filesystem": "^5.0 || ^6.0 || ^7.0",
        "symfony/process": "^5.0 || ^6.0 || ^7.0",
        "symfony/yaml": "^5.0 || ^6.0 || ^7.0"
```

In the CI :
```
 strategy:
      matrix:
        php-version: [ '8.1', '8.2', '8.3' ]
        coverage-driver: [ pcov ]
        symfony-require: [ '^5', '^6', '^7' ]
```
